services:
  db:
    image: postgres
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_PASSWORD: batata
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - .data:/var/lib/postgresql/data
    shm_size: 128mb
    ports:
      - '5435:5432'

  web:
    build: "/."
    container_name: php-container
    restart: always
    volumes:
      - .:/var/www/tcc
    # command: bash && composer du
    ports:
      - "80:80"
    depends_on:
      - db
